package domain

import "errors"

var (
	ErrInvalidID                 = errors.New("invalid id")
	ErrInvalidSlug               = errors.New("invalid slug")
	ErrInvalidTitle              = errors.New("invalid title")
	ErrInvalidPrice              = errors.New("invalid price")
	ErrInvalidCurrency           = errors.New("invalid currency")
	ErrInvalidDateRange          = errors.New("invalid date range")
	ErrInvalidSlots              = errors.New("invalid slots")
	ErrInvalidContactName        = errors.New("invalid contact name")
	ErrInvalidPhone              = errors.New("invalid phone")
	ErrInvalidEmail              = errors.New("invalid email")
	ErrInvalidPassword           = errors.New("invalid password")
	ErrInvalidCredentials        = errors.New("invalid credentials")
	ErrDuplicateEmail            = errors.New("duplicate email")
	ErrDuplicatePhone            = errors.New("duplicate phone")
	ErrInvalidPeopleCount        = errors.New("invalid people count")
	ErrInvalidTotalPrice         = errors.New("invalid total price")
	ErrInvalidBookingStatus      = errors.New("invalid booking status")
	ErrInvalidStatusTransition   = errors.New("invalid booking status transition")
	ErrInvalidClientName         = errors.New("invalid client name")
	ErrInvalidRating             = errors.New("invalid rating")
	ErrInvalidReviewText         = errors.New("invalid review text")
	ErrInvalidEntityType         = errors.New("invalid entity type")
	ErrInvalidExternalSystem     = errors.New("invalid external system")
	ErrInvalidExternalEntityType = errors.New("invalid external entity type")
	ErrInvalidExternalEntityID   = errors.New("invalid external entity id")
	ErrInvalidSyncStatus         = errors.New("invalid sync status")
	ErrInvalidEventType          = errors.New("invalid event type")
	ErrInvalidOutboxStatus       = errors.New("invalid outbox status")
	ErrInvalidBlockType          = errors.New("invalid block type")
	ErrInvalidPath               = errors.New("invalid path")
	ErrInvalidExcerpt            = errors.New("invalid excerpt")
	ErrInvalidArticleBody        = errors.New("invalid article body")
	ErrInvalidPublishedAt        = errors.New("invalid published at")
	ErrDuplicateSlug             = errors.New("duplicate slug")
	ErrDuplicatePath             = errors.New("duplicate path")
	ErrInsufficientSlots         = errors.New("insufficient slots")
	ErrNotFound                  = errors.New("not found")
	ErrInvalidSupportMessage     = errors.New("invalid support message")
	ErrInvalidSupportSender      = errors.New("invalid support sender")
	ErrInvalidTelegramUsername      = errors.New("invalid telegram username")
	ErrInvalidTelegramChatID        = errors.New("invalid telegram chat id")
	ErrInvalidNotificationChannel   = errors.New("invalid notification channel")
	ErrInvalidNotificationAddress   = errors.New("invalid notification address")
	ErrInvalidNotificationEvent     = errors.New("invalid notification event")
	ErrInvalidAdminRoleName         = errors.New("invalid admin role name")
	ErrInvalidPermission            = errors.New("invalid permission")
	ErrForbidden                    = errors.New("forbidden")
	ErrDuplicateAdminRoleName       = errors.New("duplicate admin role name")
)
