#cloud-config
package_update: true
packages:
  - ca-certificates
  - curl
  - rsync

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable --now docker
  - usermod -aG docker yc-user
  - mkdir -p /opt/palomnik
  - chown yc-user:yc-user /opt/palomnik
